name: Build, Test and Publish Artifact

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - uses: action/checkout@v2
  - name: Setup .Net
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version:5.0.x
